version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/smartHouseFront
    ports:
      - "3000:80"
    volumes:
      - ./frontend/smartHouseFront:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb+srv://yosr:yosr@smarthouse.1xebt.mongodb.net/smarthouse?retryWrites=true&w=majority
      PORT: 3000
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
